### ISSUE TITLE
Issue in running the code

### ISSUE THREAD

**Issue by JafferWilson** [OpenCCG/openccg#9]
```
Buildfile: /home/aims-whm/openccg/ccgbank/build-ps.xml

init:

prepare-novel-dir:

check-for-tok:

prepare-novel-text:

check-truecased-text:

truecase-text:
     [echo] Truecasing text for NER tagging into file ./data/novel/two-sents.dir/truecased-text
     [java] Could not find opennlp.ccg.lexicon.TrueCaser. Make sure you have it in your classpath
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:140)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:834)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:228)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:137)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:110)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:857)
     [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:236)
     [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
     [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
     [java] Java Result: -1

check-for-ner:

BUILD FAILED
/home/aims-whm/openccg/ccgbank/build-ps.xml:371: /home/aims-whm/openccg/ccgbank/data/novel/two-sents.dir/truecased-text not found.

Total time: 0 seconds
```
Above is the log. I could not understand why the problem is arising.

**Comment by JafferWilson** [comment]
Yeah got it now.... :)
